# Generated by Django 4.2.4 on 2023-10-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttbl',
            name='rfidno',
            field=models.IntegerField(blank=True, null=True, verbose_name='RFID No.'),
        ),
    ]
