# Generated by Django 4.2.4 on 2023-11-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_receptionisttbl_gender'),
        ('patientapp', '0002_patienttbl_rfidno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttbl',
            name='rfidno',
        ),
        migrations.CreateModel(
            name='Appointmenttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptdate', models.DateField(null=True, verbose_name='Appointment Date')),
                ('active', models.IntegerField(blank=True, null=True)),
                ('hospitalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospitaltbl', verbose_name='Title')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patienttbl', verbose_name='Name')),
                ('vaccineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.vaccinetbl', verbose_name='Vaccine')),
            ],
        ),
    ]
