# Generated by Django 4.2.4 on 2023-11-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_remove_patienttbl_rfidno_appointmenttbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttbl',
            name='patientid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientapp.patienttbl', verbose_name='Name'),
        ),
    ]
