# Generated by Django 4.2.4 on 2023-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_appointmenttbl_childname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttbl',
            name='indt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmenttbl',
            name='outdt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmenttbl',
            name='rfidno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
