# Generated by Django 5.2.10 on 2026-03-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_appointmenttbl_indt_appointmenttbl_outdt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttbl',
            name='relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relation'),
        ),
        migrations.CreateModel(
            name='Childtbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childname', models.CharField(max_length=255, verbose_name='Child Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patientapp.patienttbl', verbose_name='Parent')),
            ],
        ),
    ]
