# Generated by Django 5.2.10 on 2026-03-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_alter_receptionisttbl_hospitalid'),
        ('patientapp', '0007_patienttbl_relation_childtbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttbl',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patientapp.childtbl', verbose_name='Child Profile'),
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_record', to='patientapp.appointmenttbl', verbose_name='Appointment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patientapp.childtbl', verbose_name='Child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.vaccinetbl', verbose_name='Vaccine')),
            ],
            options={
                'unique_together': {('child', 'vaccine')},
            },
        ),
    ]
