# Generated by Django 5.2.10 on 2026-03-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_appointmenttbl_child_vaccinationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(max_length=50, verbose_name='Type')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='Related ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patientapp.patienttbl', verbose_name='Patient')),
            ],
        ),
    ]
