# Generated by Django 5.2.12 on 2026-03-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttbl',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed by Patient'),
        ),
        migrations.AddField(
            model_name='appointmenttbl',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder Sent'),
        ),
        migrations.AlterField(
            model_name='appointmenttbl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='childtbl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patienttbl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
