# Generated by Django 5.2.12 on 2026-06-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0010_appointmenttbl_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childtbl',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Blood Group'),
        ),
        migrations.CreateModel(
            name='VaccineCardUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vaccine_cards/', verbose_name='Vaccine Card Image')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='Extracted Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_uploads', to='patientapp.patienttbl', verbose_name='Patient')),
            ],
        ),
    ]
