# Generated by Django 5.0.14 on 2026-08-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientapp", "0011_childtbl_blood_group_vaccinecardupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttbl",
            name="apttime",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Appointment Time"
            ),
        ),
        migrations.AddField(
            model_name="patienttbl",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="patienttbl",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
    ]
