# Generated by Django 5.0.14 on 2026-08-09 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0011_rfid_workflow_redesign"),
        ("patientapp", "0013_rfidcard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rfidcard",
            name="child",
        ),
        migrations.AddField(
            model_name="appointmenttbl",
            name="checkin_receptionist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkin_appointments",
                to="hospitalapp.receptionisttbl",
                verbose_name="Check-in Receptionist",
            ),
        ),
        migrations.AddField(
            model_name="appointmenttbl",
            name="checkin_rfid",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Check-in RFID"
            ),
        ),
        migrations.AddField(
            model_name="appointmenttbl",
            name="checkin_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Check-in Time"
            ),
        ),
        migrations.AddField(
            model_name="appointmenttbl",
            name="completion_receptionist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completion_appointments",
                to="hospitalapp.receptionisttbl",
                verbose_name="Completion Receptionist",
            ),
        ),
        migrations.AddField(
            model_name="appointmenttbl",
            name="completion_rfid",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Completion RFID"
            ),
        ),
        migrations.AddField(
            model_name="appointmenttbl",
            name="completion_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completion Time"
            ),
        ),
        migrations.AddField(
            model_name="appointmenttbl",
            name="queue_position",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Queue Position"
            ),
        ),
        migrations.AddField(
            model_name="patienttbl",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("PENDING_HOSPITAL_REGISTRATION", "Pending Hospital Registration"),
                    ("RFID_ASSIGNED", "RFID Assigned"),
                    ("ACTIVE", "Active"),
                ],
                default="PENDING_HOSPITAL_REGISTRATION",
                max_length=30,
                verbose_name="Account Status",
            ),
        ),
        migrations.AddField(
            model_name="patienttbl",
            name="must_change_password",
            field=models.BooleanField(
                default=True, verbose_name="Must Change Password"
            ),
        ),
        migrations.AddField(
            model_name="patienttbl",
            name="registered_hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_patients",
                to="hospitalapp.hospitaltbl",
                verbose_name="Registration Hospital",
            ),
        ),
        migrations.AddField(
            model_name="rfidcard",
            name="assigned_by_hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_rfid_cards",
                to="hospitalapp.hospitaltbl",
                verbose_name="Assigned By Hospital",
            ),
        ),
        migrations.AddField(
            model_name="rfidcard",
            name="assigned_by_staff",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Assigned By Staff"
            ),
        ),
        migrations.AlterField(
            model_name="appointmenttbl",
            name="active",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="RFIDAssignmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("DEACTIVATED", "Deactivated"),
                            ("REASSIGNED", "Reassigned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(max_length=255, verbose_name="Performed By"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospitalapp.hospitaltbl",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfid_assignment_logs",
                        to="patientapp.patienttbl",
                    ),
                ),
                (
                    "rfid_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_logs",
                        to="patientapp.rfidcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CHECKED_IN", "Checked In"),
                            ("VERIFIED", "Verified"),
                            ("IN_PROGRESS", "Vaccination In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CHECKED_IN",
                        max_length=20,
                    ),
                ),
                (
                    "scan1_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="First RFID Scan Time"
                    ),
                ),
                (
                    "scan2_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Second RFID Scan Time"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="patientapp.appointmenttbl",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_transactions",
                        to="patientapp.childtbl",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_transactions",
                        to="hospitalapp.hospitaltbl",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_transactions",
                        to="patientapp.patienttbl",
                    ),
                ),
                (
                    "rfid_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_transactions",
                        to="patientapp.rfidcard",
                    ),
                ),
                (
                    "scan1_receptionist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan1_transactions",
                        to="hospitalapp.receptionisttbl",
                        verbose_name="Check-in Receptionist",
                    ),
                ),
                (
                    "scan2_receptionist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan2_transactions",
                        to="hospitalapp.receptionisttbl",
                        verbose_name="Completion Receptionist",
                    ),
                ),
            ],
        ),
    ]
