# Generated by Django 5.2.12 on 2026-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientapp", "0015_data_migrate_rfid_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmenttbl",
            name="indt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointmenttbl",
            name="outdt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
