# Generated by Django 5.0.14 on 2026-09-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientapp", "0016_alter_appointmenttbl_indt_alter_appointmenttbl_outdt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patienttbl",
            name="contactNo",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Contact"),
        ),
    ]
