# Generated by Django 4.2.4 on 2023-09-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaltbl',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profileimg', verbose_name='Profile Image'),
        ),
    ]
