# Generated by Django 4.2.4 on 2023-09-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_hospitaltbl_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinetbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccineName', models.CharField(max_length=255, verbose_name='Vaccine Name')),
                ('vaccineDescr', models.CharField(max_length=500, verbose_name='Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('hospitalId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospitaltbl')),
            ],
        ),
    ]
