# Generated by Django 4.2.4 on 2023-10-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_remove_hospitaltbl_name_hospitaltbl_dcrname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionisttbl',
            name='gender',
        ),
    ]
