# Generated by Django 4.2.4 on 2023-10-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_remove_receptionisttbl_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionisttbl',
            name='gender',
            field=models.CharField(default='Male', max_length=10, verbose_name='Gender'),
        ),
    ]
