# Generated by Django 4.2.4 on 2023-11-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_receptionisttbl_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionisttbl',
            name='hospitalid',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospitaltbl', verbose_name='Title'),
        ),
    ]
