# Generated by Django 5.2.12 on 2026-06-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_alter_receptionisttbl_hospitalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinetbl',
            name='minimum_quantity',
            field=models.IntegerField(default=5, verbose_name='Minimum Quantity'),
        ),
        migrations.AddField(
            model_name='vaccinetbl',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='hospitaltbl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receptionisttbl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinetbl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VaccineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protects_against', models.TextField(verbose_name='Protects Against')),
                ('side_effects', models.TextField(verbose_name='Common Side Effects')),
                ('warning_signs', models.TextField(verbose_name='Warning Signs')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_info', to='hospitalapp.vaccinetbl', verbose_name='Vaccine')),
            ],
        ),
    ]
