# Generated by Django 5.0.14 on 2026-08-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0009_vaccinetbl_minimum_quantity_and_more"),
        ("patientapp", "0012_appointmenttbl_apttime_patienttbl_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitaltbl",
            name="closing_time",
            field=models.TimeField(default="17:00:00", verbose_name="Closing Time"),
        ),
        migrations.AddField(
            model_name="hospitaltbl",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="hospitaltbl",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AddField(
            model_name="hospitaltbl",
            name="opening_time",
            field=models.TimeField(default="09:00:00", verbose_name="Opening Time"),
        ),
        migrations.AddField(
            model_name="hospitaltbl",
            name="slot_capacity",
            field=models.IntegerField(default=2, verbose_name="Slot Capacity"),
        ),
        migrations.AddField(
            model_name="hospitaltbl",
            name="slot_duration",
            field=models.IntegerField(default=30, verbose_name="Slot Duration (mins)"),
        ),
        migrations.CreateModel(
            name="HospitalBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="hospitalapp.hospitaltbl",
                        verbose_name="Hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Closed Date")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="hospitalapp.hospitaltbl",
                        verbose_name="Hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationRecordAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_name",
                    models.CharField(max_length=255, verbose_name="Vaccine Name"),
                ),
                (
                    "issue_type",
                    models.CharField(max_length=100, verbose_name="Issue Type"),
                ),
                ("severity", models.CharField(max_length=20, verbose_name="Severity")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "recommended_action",
                    models.TextField(verbose_name="Recommended Action"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("VERIFIED", "Verified by Staff"),
                            ("CORRECTED", "Correction Required"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_alerts",
                        to="patientapp.appointmenttbl",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_alerts",
                        to="patientapp.childtbl",
                        verbose_name="Child",
                    ),
                ),
            ],
        ),
    ]
