# Generated by Django 5.0.14 on 2026-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0010_hospitaltbl_closing_time_hospitaltbl_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinetbl",
            name="stock_quantity",
            field=models.IntegerField(default=50, verbose_name="Stock Quantity"),
        ),
    ]
