# Generated by Django 5.0.14 on 2026-08-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0011_rfid_workflow_redesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="receptionisttbl",
            name="ui_no",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                unique=True,
                verbose_name="UI Number",
            ),
        ),
    ]
