# Generated by Django 5.0.14 on 2026-09-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0012_receptionisttbl_ui_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaltbl",
            name="contactNo",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Contact"),
        ),
        migrations.AlterField(
            model_name="receptionisttbl",
            name="contactNo",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Contact"),
        ),
    ]
