# Generated by Django 5.2.12 on 2026-09-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0013_alter_hospitaltbl_contactno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaltbl",
            name="closing_time",
            field=models.TimeField(
                blank=True, default="17:00:00", null=True, verbose_name="Closing Time"
            ),
        ),
        migrations.AlterField(
            model_name="hospitaltbl",
            name="opening_time",
            field=models.TimeField(
                blank=True, default="09:00:00", null=True, verbose_name="Opening Time"
            ),
        ),
        migrations.AlterField(
            model_name="hospitaltbl",
            name="slot_capacity",
            field=models.IntegerField(
                blank=True, default=2, null=True, verbose_name="Slot Capacity"
            ),
        ),
        migrations.AlterField(
            model_name="hospitaltbl",
            name="slot_duration",
            field=models.IntegerField(
                blank=True, default=30, null=True, verbose_name="Slot Duration (mins)"
            ),
        ),
        migrations.AlterField(
            model_name="receptionisttbl",
            name="doj",
            field=models.DateField(blank=True, null=True, verbose_name="DateofJoining"),
        ),
        migrations.AlterField(
            model_name="receptionisttbl",
            name="staffimg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="staffimages",
                verbose_name="Upload Image",
            ),
        ),
    ]
