# Generated by Django 4.2.4 on 2023-09-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_adminreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admintbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField(max_length=10, verbose_name='Username')),
                ('password', models.CharField(max_length=200, verbose_name='Passwords')),
            ],
        ),
        migrations.DeleteModel(
            name='Adminreg',
        ),
    ]
