# Generated by Django 4.2.4 on 2023-09-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_admintbl_delete_adminreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintbl',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
