# Generated by Django 5.2.12 on 2026-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0007_alter_admintbl_id_alter_area_id_alter_city_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintbl",
            name="password",
            field=models.CharField(max_length=200, verbose_name="Password"),
        ),
    ]
